//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CĐCNPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhienDungPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhienDungPhong()
        {
            this.YC_dichvu = new HashSet<YC_dichvu>();
        }
    
        public int ID { get; set; }
        public string MSPhong { get; set; }
        public Nullable<System.DateTime> Ngaydung { get; set; }
        public Nullable<System.TimeSpan> Batdau { get; set; }
        public Nullable<System.TimeSpan> Ketthuc { get; set; }
        public Nullable<bool> Thanhtoan { get; set; }
        public Nullable<int> Dongia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YC_dichvu> YC_dichvu { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
