//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CĐCNPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class YC_dichvu
    {
        public string MaDV { get; set; }
        public int ID_Phien { get; set; }
        public Nullable<int> Soluong { get; set; }
    
        public virtual Dichvu Dichvu { get; set; }
        public virtual PhienDungPhong PhienDungPhong { get; set; }
    }
}
